version: 2.1
executors:
  docker-executor:
    docker:
      - image: setup:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: npm install
      - run: composer install
      - run: cp .env.example .env
      - run: php artisan key:generate

  test:
    executor: docker-executor
    steps:
      - checkout
      - run: vendor/bin/phpunit

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build